<?xml version="1.0"?>
<robot name="lidar_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Robot Params -->
  <xacro:property name="body_length" value="0.4"/>
  <xacro:property name="body_width" value="0.3"/>
  <xacro:property name="body_height" value="0.1"/> 
  <xacro:property name="wheel_radius" value="0.08"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="wheel_length_gap" value="0.05"/>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x y wheel_rotate axix">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
        <mass value="0.2"/>
        <!-- <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/> -->
        <inertia ixx="0.001633" ixy="0" ixz="0" iyy="0.001633" iyz="0" izz="0.0016"/>
      </inertial>
    </link>
    
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${x} ${y} 0" rpy="${wheel_rotate} 0 0"/>
      <limit effort="50" velocity="20" lower="-3.14" upper="3.14"/>
      <axis xyz="0 0 ${axix}"/>
      <dynamics damping="0.1" friction="0.1"/>
      <safety_controller soft_lower_limit="-1.0" soft_upper_limit="1.0" k_position="100" k_velocity="10"/>
      <calibration>
        <rising>0.0</rising>
        <falling>0.0</falling>
      </calibration>  
    </joint>

    <gazebo reference="${prefix}_wheel">
      <visual name="${prefix}_wheel_dot">
        <origin xyz="${wheel_radius} 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.05" length="0.05"/>
        </geometry>
        <material>Gazebo/Red</material>
      </visual>
    </gazebo>
  </xacro:macro>


  <!-- Materials -->
  <material name="blue">
    <color rgba="0 0 1 1"/>
  </material> 
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>   
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>   
  <material name="green">
    <color rgba="0 1 0 1"/>
  </material>
  <material name="yellow">
    <color rgba="1 1 0 1"/> 
  </material>
  <material name="neon_pink">
    <color rgba="1.0 0.2 0.6 1"/>
  </material>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${wheel_radius/2}"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.04167" ixy="0" ixz="0" iyy="0.07083" iyz="0" izz="0.10417"/>
    </inertial>
  </link>

  <!-- Wheels -->
  <xacro:wheel prefix="left_front" x="-${body_length/2 - wheel_length_gap}" y="${body_width/2 + wheel_width/2}" wheel_rotate="-1.570796" axix="1"/>
  <xacro:wheel prefix="left_rear" x="${body_length/2 - wheel_length_gap}" y="${body_width/2 + wheel_width/2}" wheel_rotate="-1.570796" axix="1"/>
  <xacro:wheel prefix="right_front" x="-${body_length/2 - wheel_length_gap}" y="-${body_width/2 + wheel_width/2}" wheel_rotate="1.570796" axix="-1"/>
  <xacro:wheel prefix="right_rear" x="${body_length/2 - wheel_length_gap}" y="-${body_width/2 + wheel_width/2}" wheel_rotate="1.570796" axix="-1"/> 

  <gazebo reference="base_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="left_front_wheel">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="left_rear_wheel">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
    <material>Gazebo/Green</material>
  </gazebo>
  <gazebo reference="right_front_wheel">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="right_rear_wheel">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
    <material>Gazebo/Green</material>
  </gazebo>


  <!-- left_front_wheel -->
  <transmission name="left_front_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_front_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_front_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </actuator>
  </transmission>
  <gazebo reference="left_front_wheel_joint">
    <provideFeedback>true</provideFeedback>
  </gazebo>



  <!-- left_rear_wheel -->
  <transmission name="left_rear_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_rear_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_rear_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </actuator>
  </transmission>
  <gazebo reference="left_rear_wheel_joint">
    <provideFeedback>true</provideFeedback>
  </gazebo>


  <!-- right_front_wheel -->
  <transmission name="right_front_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_front_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_front_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </actuator>
  </transmission>
  <gazebo reference="right_front_wheel_joint">
    <provideFeedback>true</provideFeedback>
  </gazebo>


  <!-- right_rear_wheel -->
  <transmission name="right_rear_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_rear_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_rear_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </actuator>
  </transmission>
  <gazebo reference="right_rear_wheel_joint">
    <provideFeedback>true</provideFeedback>
  </gazebo>



  <!-- LiDAR Sensor (Hokuyo style) -->
  <link name="laser_link">
    <visual>
      <geometry>
        <cylinder radius="0.03" length="0.05"/>
      </geometry>
      <material name="black"/>
    </visual>
    <origin xyz="0 0 ${body_height/2 + 0.05}" rpy="0 0 0"/>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_link"/>
    <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="laser_link">
    <material>Gazebo/neon_pink</material>
  </gazebo>

  <!-- Plugin to load ros_control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
    <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <updateRate>50.0</updateRate>
      <robotNamespace>/</robotNamespace>
      <leftJoint>left_front_wheel_joint</leftJoint>
      <leftJoint>left_rear_wheel_joint</leftJoint>
      <rightJoint>right_front_wheel_joint</rightJoint>
      <rightJoint>right_rear_wheel_joint</rightJoint>
      <wheelSeparation>0.32</wheelSeparation>
      <wheelDiameter>0.16</wheelDiameter>
      <robotBaseFrame>base_link</robotBaseFrame>
      <rosDebugLevel>1</rosDebugLevel>
      <publishWheelTF>true</publishWheelTF>
      <publishOdomTF>true</publishOdomTF>
      <publishWheelJointState>true</publishWheelJointState>
      <wheelAcceleration>1.0</wheelAcceleration>
      <wheelTorque>20</wheelTorque>
      <odometrySource>odom</odometrySource>
      <publishTf>1</publishTf>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <broadcastTF>true</broadcastTF>
      <covariance_x>0.0001</covariance_x>
      <covariance_y>0.0001</covariance_y>
      <covariance_yaw>0.0001</covariance_yaw>
    </plugin>
  </gazebo>

</robot>
