obstacle_range: 5.5
raytrace_range: 6.0
footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]] # Adjust to your robot's footprint
inflation_radius: 0.5
observation_sources: laser_scan_sensor
laser_scan_sensor:
  sensor_frame: laser_link
  data_type: LaserScan
  topic: /scan
  marking: true
  clearing: true