DWAPlannerROS:
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  max_vel_x: 1.0 # Match teleop max speed
  min_vel_x: -0.5
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  holonomic_robot: false
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal: true