
robot_wheel_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_front_wheel_joint'
  right_wheel: 'right_front_wheel_joint'
  # left_wheel: ['left_front_wheel_joint', 'left_rear_wheel_joint']
  # right_wheel: ['right_front_wheel_joint', 'right_rear_wheel_joint']

  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  enable_odom_tf: false
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 20.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 25.0   # rad/s^2

left_rear_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_rear_wheel_joint
  pid:
    p: 5.0
    i: 1.0
    d: 0.0

right_rear_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_rear_wheel_joint
  pid:
    p: 5.0
    i: 1.0
    d: 0.0

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

gazebo_ros_control:
  pid_gains:
    left_front_wheel_joint:
      p: 5.0
      i: 1.0
      d: 0.0
    left_rear_wheel_joint:
      p: 5.0
      i: 1.0
      d: 0.0
    right_front_wheel_joint:
      p: 5.0
      i: 1.0
      d: 0.0
    right_rear_wheel_joint:
      p: 5.0
      i: 1.0
      d: 0.0